### ISSUE TITLE
[Module]: multi-hub networking

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azure-modules#8]
Speaking to @grayzu, suggested raising this here. Perhaps it should be an issue template?

This issue is to track the request to create a hub & spoke tfvm. It has been created to avoid duplication of effort.

In the Azure Landing Zones team, we have a requirement to deploy hub & spoke network architectures.

I propose the following top level functional spec items:

* Create n number of hub virtual networks with supplied address spaces, locations and resource groups.
* For any hub network:
  * Supply custom DNS servers
  * optionally create full mesh peering with other hubs
  * Ability to associate IP supernets to each hub, with the module able to process this data and create route tables in peered hubs.
  * Optional linking to DDoS plan
  * Optional linking to private DNS zones
  * Optional Deployment of Azure Firewall with ability to link to an existing azure firewall policy
  * Optional deployment of ER GW in a hub network
  * Optional deployment of P2S GW in a hub network

/cc @jtracey93

Am happy to take on the work for this, using this issue to track

**Comment by lonegunmanb** [comment]
Hi @matt-FFFFFF, since we've got verified modules to create virtual network and corresponding subnets:([terraform-azurerm-network](https://github.com/Azure/terraform-azurerm-network) & [terraform-azurerm-subnets](https://github.com/Azure/terraform-azurerm-subnets)), maybe we should leave the creation of subnets to these modules?

My thought on "which resource should be declared in a module" is [here](https://github.com/jiaweitao001/terraform-azure-modules/blob/add_codex/codex/logic_code/resource.md#what-kind-of-resource-should-be-declared-in-a-module):

>The criterion for determining whether a resource should be put into the current module is: only the resource that "belongs" to this module should be declared.

So I think the Azure Firewall should has it's own module, but the Gateway looks "belong" to this h&s peering. I'm not familiar with Azure's h&s peering, I think the most important challenge is to determine the boundary of this "h&s peering"'s domain like DDD did. The problem we're facing now is a domain design problem, it would be great if we could learn from the CAF team's case study.

Please let me know if you have further thought on this thread.

**Comment by lonegunmanb** [comment]
Additional thought:

We could design and implement several modules we need to implement a full h&s peering architecture, then we can assemble them into an complete example and submit it to [example document repo](https://github.com/Azure/terraform).

**Comment by matt-FFFFFF** [comment]
See wip here

https://github.com/Azure/terraform-azure-hubandspoke

**Comment by matt-FFFFFF** [comment]
MVP complete @lonegunmanb do we need to publish to home page?

**Comment by matt-FFFFFF** [comment]
Has been released
